### ISSUE TITLE
如何将单列Operator修改格式变为多列Operator

### ISSUE THREAD

**Issue by Emmitte** [alibaba/Alink#10]
大神们好，有个问题想请教一下，我通过Kafka011SourceStreamOp读取Kafka中的数据，但获取到message生成一列的Operator，我想对message进行解析(例如通过逗号分隔)，生成新的多列的Operator，这样该如何操作？以下为我部分代码，希望大神帮忙解答，谢谢！
`#!/usr/bin/python
# -*- coding: UTF-8 -*-
from pyalink.alink import *
import numpy as np
import pandas as pd

useLocalEnv(1)

bootstrapServer = "10.124.165.91:9092"
topic = "test_alink1"

data = Kafka011SourceStreamOp().setBootstrapServers(bootstrapServer).setTopic(topic).setStartupMode("EARLIEST").setGroupId("")

#此次可获取Kafka中message的信息，但是想对其进行解析生成新的Operator，同时不想解析成DataFrame再转Operator，因为之前readme中介绍过，不要频繁切换DataFrame与Operator，效率会收到影响。
data.select("message").print()
StreamOperator.execute()`

**Comment by chengscu** [comment]
可以考虑用UDF来解析

**Comment by Emmitte** [comment]
好嘞，一会儿试一下，谢谢～发自我的华为手机-------- 原始邮件 --------主题：Re: [alibaba/Alink] 如何将单列Operator修改格式变为多列Operator (#10)发件人：Cheng Jie 收件人：alibaba/Alink 抄送：Emmitte ,Author 可以考虑用UDF来解析



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/alibaba/Alink/issues/10?email_source=notifications\u0026email_token=ADRV3EOGTJWXK5WJ7L7EYLLQW6I2NA5CNFSM4JVE44A2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEF4W3DA#issuecomment-561606028",

"url": "https://github.com/alibaba/Alink/issues/10?email_source=notifications\u0026email_token=ADRV3EOGTJWXK5WJ7L7EYLLQW6I2NA5CNFSM4JVE44A2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEF4W3DA#issuecomment-561606028",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
