### ISSUE TITLE
useRemoteEnv的正确用法到底是什么？

### ISSUE THREAD

**Issue by appleyuchi** [alibaba/Alink#101]
useRemoteEnv("Desktop", 8089, 2, flinkHome=None, localIp="Desktop", config=None)
我想在jupyter上连接flink集群，
但是这个写端口的地方，我故意写错，运行时也不报错，这到底是怎么回事?
难道不应该在连接flink集群的时候进行检查吗？
请问你们是怎么使用useRemoteEnv的呢？

我的flink集群是Desktop:8082,上面这句话故意写成8089居然没有报错，我感到十分诧异，请问我哪里错了？

**Comment by appleyuchi** [comment]
这个remote的意思是连接远程的单机，还是flink集群的remote模式？

**Comment by Fanoid** [comment]
useRemoteEnv是在真正提交作业的时候才去连接集群，有错的时候会报错。 useRemoteEnv 可以连接通过 start-cluster.sh 启动的集群。
