### ISSUE TITLE
有用Googleguava，代码

### ISSUE THREAD

**Issue by LJWxyz** [alibaba/Alink#106]
在vector types.java

package com.alibaba.alink.common;
import com.google.common.collect.HashBiMap;

是googleguava ver,几的？是guava?
我想bult jar.

**Comment by LJWxyz** [comment]
在vector types.java

package com.alibaba.alink.common;
import com.google.common.collect.HashBiMap;

是googleguava ver,几的？是guava?
我想bult jar.

**Comment by shaomengwang** [comment]
目前用的是15.0，可以考虑用shade的jar包来跑，方式可以参照[Alink首页](https://github.com/alibaba/Alink)上准备Alink算法包部分

**Comment by LJWxyz** [comment]
试了用mvn

[INFO] Reactor Summary for alink 1.1-SNAPSHOT:
[INFO]
[INFO] alink .............................................. SUCCESS [11:17 min]
[INFO] alink_core_flink-1.10_2.11 ......................... FAILURE [51:40 min]
[INFO] alink_connectors ................................... SKIPPED
[INFO] alink-connector-kafka-base ......................... SKIPPED
[INFO] alink-connector-kafka-0.10 ......................... SKIPPED
[INFO] alink-connector-kafka-0.11 ......................... SKIPPED
[INFO] alink-connector-kafka .............................. SKIPPED
[INFO] alink_connectors_hive_flink-1.10_2.11 .............. SKIPPED
[INFO] alink_examples ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:06 h
会更新。

**Comment by LJWxyz** [comment]
D:\Coding\JavaRuntimeAsset\Alink-1.1.2>mvn -Dmaven.test.skip=true clean package shade:shade
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.alibaba.alink:alink_core_flink-1.10_2.11:jar:1.1-SNAPSHOT
[WARNING] 'artifactId' contains an expression but should be a constant. @ com.alibaba.alink:alink_core_flink-${alink.flink.major.version}_${alink.scala.major.version}:1.1-SNAPSHOT, D:\Coding\JavaRuntimeAsset\Alink-1.1.2\core\pom.xml, line 12, column 17
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.alibaba.alink:alink_connectors_kafka_base_flink-1.10_2.11:jar:1.1-SNAPSHOT
[WARNING] 'artifactId' contains an expression but should be a constant. @ com.alibaba.alink:alink_connectors_kafka_base_flink-${alink.flink.major.version}_${alink.scala.major.version}:1.1-SNAPSHOT, D:\Coding\JavaRuntimeAsset\Alink-1.1.2\connectors\connector-kafka-base\pom.xml, line 12, column 17
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.alibaba.alink:alink_connectors_kafka_0.10_flink-1.10_2.11:jar:1.1-SNAPSHOT
[WARNING] 'artifactId' contains an expression but should be a constant. @ com.alibaba.alink:alink_connectors_kafka_0.10_flink-${alink.flink.major.version}_${alink.scala.major.version}:1.1-SNAPSHOT, D:\Coding\JavaRuntimeAsset\Alink-1.1.2\connectors\connector-kafka-0.10\pom.xml, line 12, column 17
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.alibaba.alink:alink_connectors_kafka_0.11_flink-1.10_2.11:jar:1.1-SNAPSHOT
[WARNING] 'artifactId' contains an expression but should be a constant. @ com.alibaba.alink:alink_connectors_kafka_0.11_flink-${alink.flink.major.version}_${alink.scala.major.version}:1.1-SNAPSHOT, D:\Coding\JavaRuntimeAsset\Alink-1.1.2\connectors\connector-kafka-0.11\pom.xml, line 12, column 17
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.alibaba.alink:alink_connectors_kafka_flink-1.10_2.11:jar:1.1-SNAPSHOT
[WARNING] 'artifactId' contains an expression but should be a constant. @ com.alibaba.alink:alink_connectors_kafka_flink-${alink.flink.major.version}_${alink.scala.major.version}:1.1-SNAPSHOT, D:\Coding\JavaRuntimeAsset\Alink-1.1.2\connectors\connector-kafka\pom.xml, line 12, column 17
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.alibaba.alink:alink_connectors_hive_flink-1.10_2.11:jar:1.1-SNAPSHOT
[WARNING] 'artifactId' contains an expression but should be a constant. @ com.alibaba.alink:alink_connectors_hive_flink-${alink.flink.major.version}_${alink.scala.major.version}:1.1-SNAPSHOT, D:\Coding\JavaRuntimeAsset\Alink-1.1.2\connectors\connector-hive\pom.xml, line 12, column 17
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.alibaba.alink:alink_examples_flink-1.10_2.11:jar:1.1-SNAPSHOT
[WARNING] 'artifactId' contains an expression but should be a constant. @ com.alibaba.alink:alink_examples_flink-${alink.flink.major.version}_${alink.scala.major.version}:1.1-SNAPSHOT, D:\Coding\JavaRuntimeAsset\Alink-1.1.2\examples\pom.xml, line 12, column 17
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] alink                                                              [pom]
[INFO] alink_core_flink-1.10_2.11                                         [jar]
[INFO] alink_connectors                                                   [pom]
[INFO] alink-connector-kafka-base                                         [jar]
[INFO] alink-connector-kafka-0.10                                         [jar]
[INFO] alink-connector-kafka-0.11                                         [jar]
[INFO] alink-connector-kafka                                              [jar]
[INFO] alink_connectors_hive_flink-1.10_2.11                              [jar]
[INFO] alink_examples                                                     [jar]
[INFO]
[INFO] ----------------------< com.alibaba.alink:alink >-----------------------
[INFO] Building alink 1.1-SNAPSHOT                                        [1/9]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ alink ---
[INFO]
[INFO] --- maven-shade-plugin:3.2.4:shade (default-cli) @ alink ---
[INFO] Replacing original artifact with shaded artifact.
[INFO]
[INFO] ------------< com.alibaba.alink:alink_core_flink-1.10_2.11 >------------
[INFO] Building alink_core_flink-1.10_2.11 1.1-SNAPSHOT                   [2/9]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ alink_core_flink-1.10_2.11 ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ alink_core_flink-1.10_2.11 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO]
[INFO] --- scala-maven-plugin:3.2.0:compile (scala-compile-first) @ alink_core_flink-1.10_2.11 ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.11
[WARNING]  org.apache.flink:flink-runtime_2.11:1.10.0 requires scala version: 2.11.12
[WARNING] Multiple versions of scala libraries detected!
[INFO] D:\Coding\JavaRuntimeAsset\Alink-1.1.2\core\src\main\java:-1: info: compiling
[INFO] D:\Coding\JavaRuntimeAsset\Alink-1.1.2\core\src\main\scala:-1: info: compiling
[INFO] Compiling 1372 source files to D:\Coding\JavaRuntimeAsset\Alink-1.1.2\core\target\classes at 1593920349712
[ERROR] error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[ERROR]         at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
[ERROR]         at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
[ERROR]         at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
[ERROR]         at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[ERROR]         at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[ERROR]         at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
[ERROR]         at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
[ERROR]         at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
[ERROR]         at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
[ERROR]         at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
[ERROR]         at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1390)
[ERROR]         at scala.tools.nsc.Global$Run.<init>(Global.scala:1242)
[ERROR]         at scala.tools.nsc.Driver.doCompile(Driver.scala:31)
[ERROR]         at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
[ERROR]         at scala.tools.nsc.Driver.process(Driver.scala:51)
[ERROR]         at scala.tools.nsc.Driver.main(Driver.scala:64)
[ERROR]         at scala.tools.nsc.Main.main(Main.scala)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR]         at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[ERROR]         at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for alink 1.1-SNAPSHOT:
[INFO]
[INFO] alink .............................................. SUCCESS [  4.511 s]
[INFO] alink_core_flink-1.10_2.11 ......................... FAILURE [ 18.387 s]
[INFO] alink_connectors ................................... SKIPPED
[INFO] alink-connector-kafka-base ......................... SKIPPED
[INFO] alink-connector-kafka-0.10 ......................... SKIPPED
[INFO] alink-connector-kafka-0.11 ......................... SKIPPED
[INFO] alink-connector-kafka .............................. SKIPPED
[INFO] alink_connectors_hive_flink-1.10_2.11 .............. SKIPPED
[INFO] alink_examples ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.405 s
[INFO] Finished at: 2020-07-04T20:39:14-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (scala-compile-first) on project alink_core_flink-1.10_2.11: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :alink_core_flink-1.10_2.11

这是用，openjdkzulu14，alinkrelease（1.12）。
flink，是必要的？
打算manualjarbuild。。会更新

**Comment by shaomengwang** [comment]
> D:\Coding\JavaRuntimeAsset\Alink-1.1.2>mvn -Dmaven.test.skip=true clean package shade:shade
> [INFO] Scanning for projects...
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for com.alibaba.alink:alink_core_flink-1.10_2.11:jar:1.1-SNAPSHOT
> [WARNING] 'artifactId' contains an expression but should be a constant. @ com.alibaba.alink:alink_core_flink-${alink.flink.major.version}_${alink.scala.major.version}:1.1-SNAPSHOT, D:\Coding\JavaRuntimeAsset\Alink-1.1.2\core\pom.xml, line 12, column 17 [WARNING] [WARNING] Some problems were encountered while building the effective model for com.alibaba.alink:alink_connectors_kafka_base_flink-1.10_2.11:jar:1.1-SNAPSHOT [WARNING] 'artifactId' contains an expression but should be a constant. @ com.alibaba.alink:alink_connectors_kafka_base_flink-${alink.flink.major.version}_${alink.scala.major.version}:1.1-SNAPSHOT, D:\Coding\JavaRuntimeAsset\Alink-1.1.2\connectors\connector-kafka-base\pom.xml, line 12, column 17
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for com.alibaba.alink:alink_connectors_kafka_0.10_flink-1.10_2.11:jar:1.1-SNAPSHOT
> [WARNING] 'artifactId' contains an expression but should be a constant. @ com.alibaba.alink:alink_connectors_kafka_0.10_flink-${alink.flink.major.version}_${alink.scala.major.version}:1.1-SNAPSHOT, D:\Coding\JavaRuntimeAsset\Alink-1.1.2\connectors\connector-kafka-0.10\pom.xml, line 12, column 17 [WARNING] [WARNING] Some problems were encountered while building the effective model for com.alibaba.alink:alink_connectors_kafka_0.11_flink-1.10_2.11:jar:1.1-SNAPSHOT [WARNING] 'artifactId' contains an expression but should be a constant. @ com.alibaba.alink:alink_connectors_kafka_0.11_flink-${alink.flink.major.version}_${alink.scala.major.version}:1.1-SNAPSHOT, D:\Coding\JavaRuntimeAsset\Alink-1.1.2\connectors\connector-kafka-0.11\pom.xml, line 12, column 17
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for com.alibaba.alink:alink_connectors_kafka_flink-1.10_2.11:jar:1.1-SNAPSHOT
> [WARNING] 'artifactId' contains an expression but should be a constant. @ com.alibaba.alink:alink_connectors_kafka_flink-${alink.flink.major.version}_${alink.scala.major.version}:1.1-SNAPSHOT, D:\Coding\JavaRuntimeAsset\Alink-1.1.2\connectors\connector-kafka\pom.xml, line 12, column 17 [WARNING] [WARNING] Some problems were encountered while building the effective model for com.alibaba.alink:alink_connectors_hive_flink-1.10_2.11:jar:1.1-SNAPSHOT [WARNING] 'artifactId' contains an expression but should be a constant. @ com.alibaba.alink:alink_connectors_hive_flink-${alink.flink.major.version}_${alink.scala.major.version}:1.1-SNAPSHOT, D:\Coding\JavaRuntimeAsset\Alink-1.1.2\connectors\connector-hive\pom.xml, line 12, column 17
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for com.alibaba.alink:alink_examples_flink-1.10_2.11:jar:1.1-SNAPSHOT
> [WARNING] 'artifactId' contains an expression but should be a constant. @ com.alibaba.alink:alink_examples_flink-${alink.flink.major.version}_${alink.scala.major.version}:1.1-SNAPSHOT, D:\Coding\JavaRuntimeAsset\Alink-1.1.2\examples\pom.xml, line 12, column 17
> [WARNING]
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING]
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING]
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Build Order:
> [INFO]
> [INFO] alink [pom]
> [INFO] alink_core_flink-1.10_2.11 [jar]
> [INFO] alink_connectors [pom]
> [INFO] alink-connector-kafka-base [jar]
> [INFO] alink-connector-kafka-0.10 [jar]
> [INFO] alink-connector-kafka-0.11 [jar]
> [INFO] alink-connector-kafka [jar]
> [INFO] alink_connectors_hive_flink-1.10_2.11 [jar]
> [INFO] alink_examples [jar]
> [INFO]
> [INFO] ----------------------< com.alibaba.alink:alink >-----------------------
> [INFO] Building alink 1.1-SNAPSHOT [1/9]
> [INFO] --------------------------------[ pom ]---------------------------------
> [INFO]
> [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ alink ---
> [INFO]
> [INFO] --- maven-shade-plugin:3.2.4:shade (default-cli) @ alink ---
> [INFO] Replacing original artifact with shaded artifact.
> [INFO]
> [INFO] ------------< com.alibaba.alink:alink_core_flink-1.10_2.11 >------------
> [INFO] Building alink_core_flink-1.10_2.11 1.1-SNAPSHOT [2/9]
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO]
> [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ alink_core_flink-1.10_2.11 ---
> [INFO]
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ alink_core_flink-1.10_2.11 ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 4 resources
> [INFO]
> [INFO] --- scala-maven-plugin:3.2.0:compile (scala-compile-first) @ alink_core_flink-1.10_2.11 ---
> [WARNING] Expected all dependencies to require Scala version: 2.11.11
> [WARNING] org.apache.flink:flink-runtime_2.11:1.10.0 requires scala version: 2.11.12
> [WARNING] Multiple versions of scala libraries detected!
> [INFO] D:\Coding\JavaRuntimeAsset\Alink-1.1.2\core\src\main\java👎 info: compiling
> [INFO] D:\Coding\JavaRuntimeAsset\Alink-1.1.2\core\src\main\scala👎 info: compiling
> [INFO] Compiling 1372 source files to D:\Coding\JavaRuntimeAsset\Alink-1.1.2\core\target\classes at 1593920349712
> [ERROR] error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
> [ERROR] at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
> [ERROR] at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
> [ERROR] at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
> [ERROR] at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
> [ERROR] at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
> [ERROR] at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
> [ERROR] at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
> [ERROR] at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
> [ERROR] at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
> [ERROR] at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
> [ERROR] at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1390)
> [ERROR] at scala.tools.nsc.Global$Run.(Global.scala:1242)
> [ERROR] at scala.tools.nsc.Driver.doCompile(Driver.scala:31)
> [ERROR] at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
> [ERROR] at scala.tools.nsc.Driver.process(Driver.scala:51)
> [ERROR] at scala.tools.nsc.Driver.main(Driver.scala:64)
> [ERROR] at scala.tools.nsc.Main.main(Main.scala)
> [ERROR] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [ERROR] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [ERROR] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [ERROR] at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> [ERROR] at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
> [ERROR] at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary for alink 1.1-SNAPSHOT:
> [INFO]
> [INFO] alink .............................................. SUCCESS [ 4.511 s]
> [INFO] alink_core_flink-1.10_2.11 ......................... FAILURE [ 18.387 s]
> [INFO] alink_connectors ................................... SKIPPED
> [INFO] alink-connector-kafka-base ......................... SKIPPED
> [INFO] alink-connector-kafka-0.10 ......................... SKIPPED
> [INFO] alink-connector-kafka-0.11 ......................... SKIPPED
> [INFO] alink-connector-kafka .............................. SKIPPED
> [INFO] alink_connectors_hive_flink-1.10_2.11 .............. SKIPPED
> [INFO] alink_examples ..................................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 25.405 s
> [INFO] Finished at: 2020-07-04T20:39:14-07:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (scala-compile-first) on project alink_core_flink-1.10_2.11: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR] mvn -rf :alink_core_flink-1.10_2.11
> 
> 这是用，openjdkzulu14，alinkrelease（1.12）。
> flink，是必要的？
> 打算manualjarbuild。。会更新

这个是不是因为机器没有配置scala引起的

**Comment by LJWxyz** [comment]
是的，我没放Scala进classpath。
必要的？

**Comment by shaomengwang** [comment]
scala是必要的，另也有可能是openjdk的版本问题，可以试一下java8对应的openjdk版本

**Comment by ZhangYuef** [comment]
@LJWxyz flink应该不用手动安装，alink项目里已经包含需要的flink源码了

**Comment by LJWxyz** [comment]
alink 因该没有 jar在maven repo 吧..所以我就需要compile 和pack jar 不是吗？

**Comment by shaomengwang** [comment]
> alink 因该没有 jar在maven repo 吧..所以我就需要compile 和pack jar 不是吗？

每次发布都有发布对应的jar在maven repo
