### ISSUE TITLE
one hot encode a little optimization

### ISSUE THREAD

**Issue by bai0335** [alibaba/Alink#112]
in one hot encode , there is no need count and filte when the threshold less than 1.

code is :
    DataSet<Tuple3<Integer, String, Long>> countTokens = StringIndexerUtil.countTokens(inputRows, true)
			.filter(new FilterFunction<Tuple3<Integer, String, Long>>() {
				@Override
				public boolean filter(Tuple3<Integer, String, Long> value) {
					return value.f2 >= thresholdArray[value.f0];
				}
			});

**Comment by lqb11** [comment]
Thanks, we'll optimize it later.
