### ISSUE TITLE
NPE in one hot test

### ISSUE THREAD

**Issue by bai0335** [alibaba/Alink#113]
![image](https://user-images.githubusercontent.com/18212330/87682630-a552e200-c7b2-11ea-9342-7a1ec47d58e7.png)

line 441 Row.of(null)  meet   NPE

**Comment by lqb11** [comment]
Which FLINK version do you use?

**Comment by bai0335** [comment]
FLINK version is  1.10.0
Row.of(null) this method  get the value.length first, if we pass a null value , it will throw NPE

**Comment by lqb11** [comment]
You can pull the latest code, in Issue#111, this problem has been fixed.
