### ISSUE TITLE
是否支持在线深度学习

### ISSUE THREAD

**Issue by aimetrics** [alibaba/Alink#12]
浏览了example和文档之后，发现在线学习是应用在浅层模型。不支持深度学习难免挂万漏一。

**Comment by weibozhao** [comment]
> 浏览了example和文档之后，发现在线学习是应用在浅层模型。不支持深度学习难免挂万漏一。

Alink目前不支持在线深度学习。

**Comment by aimetrics** [comment]
> > 浏览了example和文档之后，发现在线学习是应用在浅层模型。不支持深度学习难免挂万漏一。
> 
> Alink目前不支持在线深度学习。

有计划什么时候支持吗?

**Comment by aimetrics** [comment]
> > 浏览了example和文档之后，发现在线学习是应用在浅层模型。不支持深度学习难免挂万漏一。
> 
> Alink目前不支持在线深度学习。

不支持，是为了保持技术上的领先吗?

**Comment by weibozhao** [comment]
> > > 浏览了example和文档之后，发现在线学习是应用在浅层模型。不支持深度学习难免挂万漏一。
> > 
> > 
> > Alink目前不支持在线深度学习。
> 
> 不支持，是为了保持技术上的领先吗?

深度学习是我们另一个项目在做的工作，Alink 重点在传统机器学习
