### ISSUE TITLE
Allow to inject existed flink env 

### ISSUE THREAD

**Issue by zjffdu** [alibaba/Alink#13]
For now Alink would create env by itself, which make it difficult to integrate with other tools/framework. It would be nice to allow alink to use the env created by others.

**Comment by qiuxiafei** [comment]
Alink supports custom env. Please take a look at [MLEnvironmentFactory. setDefault](https://github.com/alibaba/Alink/blob/994b3f291d4dc4b885e17598d81014319f520775/core/src/main/java/com/alibaba/alink/common/MLEnvironmentFactory.java#L71) and [MLEnvironmentFactory. registerMLEnvironment](https://github.com/alibaba/Alink/blob/994b3f291d4dc4b885e17598d81014319f520775/core/src/main/java/com/alibaba/alink/common/MLEnvironmentFactory.java#L94).

**Comment by zjffdu** [comment]
It is MLEnvrionment, I mean to inject Flink's Environment

**Comment by qiuxiafei** [comment]
`MLEnvironment` is just a simple wrapper class. One can easily create an `MLEnvironment` from Flink's `ExecutionEnvironment` with [one of it's constructors](https://github.com/alibaba/Alink/blob/994b3f291d4dc4b885e17598d81014319f520775/core/src/main/java/com/alibaba/alink/common/MLEnvironment.java#L58).

**Comment by Fanoid** [comment]
In the latest PyAlink, you can also inject PyFlink envs (benv, btenv, senv, stenv) using useCustomEnv.
But PyFlink has to load Alink jars in advance.
