### ISSUE TITLE
文档有错误

### ISSUE THREAD

**Issue by edclol** [alibaba/Alink#135]
/home/edc/IdeaProjects/Alink/docs/cn/samplewithsizebatchop.md
/home/edc/IdeaProjects/Alink/docs/en/samplewithsizebatchop.md
示例的函数名称错误，不应该是SampleBatchOp，应该是SampleWithSizeBatchOp

**Comment by ZhangYuef** [comment]
Correct the document in PR #146

**Comment by shaomengwang** [comment]
fixed 7d05a7c8f351834ab123cb1b46d7331f349029e0
