### ISSUE TITLE
Alink支持从模型启动吗

### ISSUE THREAD

**Issue by erienniu** [alibaba/Alink#139]
从文档和example来看，各种算法必须传入一定的原始数据训练后才能使用。
当我们训练集大的时候是否会延长启动时间？（没有线上测试过，猜测）
特别是对于在线预测，是否可以传入某些模型冷启动？

**Comment by shaomengwang** [comment]
可以看在线预测组件的构造函数上对应都可以传入一个BatchOperator，这个Op可以作为冷启动模型
