### ISSUE TITLE
complier bug:  Failure to find org.apache.flink:flink-jdbc_2.11:jar:1.11.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1] [ERROR] 

### ISSUE THREAD

**Issue by chenxingqiang** [alibaba/Alink#149]
Failure to find org.apache.flink:flink-jdbc_2.11:jar:1.11.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]

**Comment by shaomengwang** [comment]
ref: https://stackoverflow.com/questions/4856307/when-maven-says-resolution-will-not-be-reattempted-until-the-update-interval-of
