### ISSUE TITLE
Is there any way to train models with streaming data?

### ISSUE THREAD

**Issue by rpgincoming** [alibaba/Alink#156]
Hello,  I was attracted by Alink because it advertized that Alink is a batch-stream integrated machine learning platform.
But it seems that almost all training operators in Alink is "xxxTrainBatchOp". Is there any way to make them work with streaming data like Kafka streams? Thanks for answering!

**Comment by shaomengwang** [comment]
xxxTrainBatchOp could not work with streaming data right now.

Ftrl can work with the streaming data. please ref: https://github.com/alibaba/Alink/blob/master/pyalink/ftrl_demo.ipynb
