### ISSUE TITLE
WorldCountBatchup 环境错误

### ISSUE THREAD

**Issue by wanglei4687** [alibaba/Alink#157]
具体信息：
Could not found the Java class 'com.alibaba.alink.common.MLEnvironment'. The Java dependencies could be specified via command line argument '--jarfile' or the config option 'pipeline.jars'
代码：
`    resetEnv()
    env = getMLEnv()

    df = pd.DataFrame.from_records(data )
    source = BatchOperator.fromDataframe(df, "id string, content string")
    wordCountBatchOp = WordCountBatchOp() \
        .setSelectedCol("content") \
        .setWordDelimiter(" ") \
        .linkFrom(source)
    wordCountBatchOp.print()
    wordCountBatchOp.execute()`

**Comment by wanglei4687** [comment]
useRemoteEnv 是可以运行的

**Comment by Fanoid** [comment]
可以放一下你的完整运行代码吗？  有没有将 pyalink 安装目录下lib下的 jar 包放到 flink 的 lib 目录下呢？

**Comment by wanglei4687** [comment]
> 可以放一下你的完整运行代码吗？ 有没有将 pyalink 安装目录下lib下的 jar 包放到 flink 的 lib 目录下呢？
