### ISSUE TITLE
MySqlSourceBatchOp is not defined

### ISSUE THREAD

**Issue by bingfeng2004** [alibaba/Alink#158]
version:Alink-1.3.0-flink-1.11
from pyalink.alink import *
  File "<ipython-input-6-36fecb05ca8b>", line 1, in <module>
    data = MySqlSourceBatchOp()\

NameError: name 'MySqlSourceBatchOp' is not defined

这里无法使用MySqlSourceBatchOp是什么原因

**Comment by shaomengwang** [comment]
从1.2 到 1.3版本中，去掉了MySqlSourceBatchOp，统一使用CatalogSourceBatchOp代替了
