### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by yijiang1121** [alibaba/Alink#16]
The last test (testReadEasModel) at CsvSourceSinkTest.java fails. It's likely that the path cannot be reached in the US.

String path = "http://test-region.oss-cn-hangzhou-zmf.aliyuncs.com/alink_model_export/Alink-Expr-pre-6339/226607/model_data.csv"

**Comment by chengscu** [comment]
> The last test (testReadEasModel) at CsvSourceSinkTest.java fails. It's likely that the path cannot be reached in the US.
> 
> String path = "http://test-region.oss-cn-hangzhou-zmf.aliyuncs.com/alink_model_export/Alink-Expr-pre-6339/226607/model_data.csv"

Thanks, we will fix this problem in the next release.

**Comment by shaomengwang** [comment]
see c93206d
