### ISSUE TITLE
ftrl_demo.ipynb执行错误，Py4JError: com.alibaba.alink.operator.stream.dataproc.SplitStreamOp does not exist in the JVM

### ISSUE THREAD

**Issue by EdQzz** [alibaba/Alink#160]
linux centos7,python3.6,pyalink-1.3.0
安装pyalink后，启动jupyter
将[https://github.com/alibaba/Alink/blob/master/pyalink/ftrl_demo.ipynb](ftrl_demo)复制到jupyter中执行报错
详细错误日志如下：
Py4JError                                 Traceback (most recent call last)
<ipython-input-27-65955c9df4ac> in <module>
     34 
     35 # split stream to train and eval data
---> 36 spliter = SplitStreamOp().setFraction(0.5).linkFrom(data)
     37 train_stream_data = spliter
     38 test_stream_data = spliter.getSideOutput(0)

/usr/local/lib/python3.6/site-packages/pyalink/alink/stream/common/stream_op_3.py in __init__(self, *args, **kwargs)
    314         kwargs['CLS_NAME'] = self.CLS_NAME
    315         kwargs['OP_TYPE'] = self.OP_TYPE
--> 316         super(SplitStreamOp, self).__init__(*args, **kwargs)
    317         pass
    318 

/usr/local/lib/python3.6/site-packages/pyalink/alink/stream/base.py in __init__(self, j_op, model, *args, **kwargs)
     17         self.opType = kwargs.pop('OP_TYPE', 'FUNCTION')
     18         params = Params.from_args(*args, **kwargs)
---> 19         super(StreamOperator, self).__init__(params, name, cls_name, j_op=j_op, model=model)
     20 
     21     def linkFrom(self, *ops):

/usr/local/lib/python3.6/site-packages/pyalink/alink/common/types/bases/op_cores.py in __init__(self, params, name, cls_name, j_op, model)
     26         else:
     27             if model is None:
---> 28                 self._j_op = get_java_class(cls_name)()
     29             else:
     30                 self._j_op = get_java_class(cls_name)(model.get_j_obj())

/usr/local/lib/python3.6/site-packages/pyalink/alink/py4j_util.py in get_java_class(name)
     45 
     46 def get_java_class(name: str):
---> 47     return get_java_gateway().jvm.__getattr__(name)
     48 
     49 

/usr/local/lib/python3.6/site-packages/py4j/java_gateway.py in __getattr__(self, name)
   1686             message = compute_exception_message(
   1687                 "{0} does not exist in the JVM".format(name), error_message)
-> 1688             raise Py4JError(message)
   1689 
   1690 

Py4JError: com.alibaba.alink.operator.stream.dataproc.SplitStreamOp does not exist in the JVM

**Comment by shaomengwang** [comment]
最新版本中已无这个问题
