### ISSUE TITLE
【BUG】json值抽取，数字0开头的字符串经过抽取后开头的0就没有了。

### ISSUE THREAD

**Issue by JuiceZZ** [alibaba/Alink#163]
测试数据：
data = np.array([
    ["{a:boy,b:{b1:\'007\',b2:2}}"],
    ["{a:girl,b:{b1:01,b2:2}}"]])
输出：
                         str                f0   f1
0  {a:boy,b:{b1:'007',b2:2}}   boy  7
1    {a:girl,b:{b1:01,b2:2}}     girl  1
问题：输出类型不对，setOutputColTypes这个方法设置类型后也是无效的。
![1609124409941_42CA575C-57DB-4fa9-8FB2-43CC92027753](https://user-images.githubusercontent.com/17290654/103186783-e2440880-48fc-11eb-9714-86748fc1c822.png)

**Comment by shaomengwang** [comment]
data = np.array(
    [
        ['{a:boy,b:{b1:"007",b2:2}}'],
        ['{a:girl,b:{b1:"01",b2:2}}']
    ]
)

print(data)

df = pd.DataFrame({"str" : data[:, 0]})

print(df)

batchData = dataframeToOperator(df, schemaStr="str string", op_type="batch")

jsoned = JsonValueBatchOp().setJsonPath(["$.a", "$.b.b1"]).setSelectedCol("str").setOutputCols(['f0', 'f1']).setOutputColTypes(['string', 'string']).linkFrom(batchData)

jsoned.registerTableName("A")

BatchOperator.sqlQuery("select CONCAT('1', f1) as f1 from A").print()

![image](https://user-images.githubusercontent.com/44366199/108370310-7bc1d380-7237-11eb-9613-6a331fdabc95.png)

Python显示时去掉了前边的0，实际值是正确的
