### ISSUE TITLE
java如何分bin

### ISSUE THREAD

**Issue by liuwenqiang1202** [alibaba/Alink#165]
计算分bin的函数FeatureBinsCalculator.createNumericCalculator需要制定切分点splitsArray。请问如何计算切分点呢？alink里面有现成的方法嘛？

**Comment by shaomengwang** [comment]
可以使用QuantileDiscretizer

参考https://github.com/alibaba/Alink/blob/8efd04475f9573bcf0b2dda0c11b52b6559d9ab1/core/src/main/java/com/alibaba/alink/pipeline/feature/QuantileDiscretizer.java#L17
