### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable  报错

### ISSUE THREAD

**Issue by myDemoMike** [alibaba/Alink#17]
![image](https://user-images.githubusercontent.com/30686987/70605684-e93aa300-1c35-11ea-9b90-15ba1382308e.png)

java version "1.8.0_202"

**Comment by Fanoid** [comment]
> ![image](https://user-images.githubusercontent.com/30686987/70605684-e93aa300-1c35-11ea-9b90-15ba1382308e.png)
> 
> java version "1.8.0_202"

可以先把flinkHome设为None，看能不能运行成功。

**Comment by myDemoMike** [comment]
一样的效果

**Comment by myDemoMike** [comment]
一样，还是不行

**Comment by Fanoid** [comment]
> 一样，还是不行

你现在安装的pyalink版本是最新的1.0.1吗？

**Comment by myDemoMike** [comment]
> > 一样，还是不行
> 
> 你现在安装的pyalink版本是最新的1.0.1吗？

![image](https://user-images.githubusercontent.com/30686987/70679832-52bbbf80-1cd1-11ea-9d52-5adc2331a1b9.png)

**Comment by myDemoMike** [comment]
![image](https://user-images.githubusercontent.com/30686987/70679861-6c5d0700-1cd1-11ea-87e4-02384ed20fb0.png)

**Comment by myDemoMike** [comment]
> > 一样，还是不行
> 
> 你现在安装的pyalink版本是最新的1.0.1吗？

1.0-flink-1.9.0-scala-2.11

**Comment by Fanoid** [comment]
请下载最新的版本进行安装。

**Comment by myDemoMike** [comment]
> > > 一样，还是不行
> > 
> > 
> > 你现在安装的pyalink版本是最新的1.0.1吗？
> 
> 1.0-flink-1.9.0-scala-2.11



> 请下载最新的版本进行安装。

是这个问题，解决了，谢谢！！！
