### ISSUE TITLE
I have a few questions.

### ISSUE THREAD

**Issue by dragonblare** [alibaba/Alink#185]
Hello. I have a few questions and posted them here.
Questions:
1. When I build a standalone cluster with Flink, if I put the lib folder of alink into the lib folder of Flink other than jobmanager, I cannot connect to jobmanager.
Is it OK to put the lib folder of alink into the lib folder of Flink only on the jobmanager side?

2. I'm currently doing machine learning, but I'm not sure if the data is too large, or if "An error occurred while calling z:com.alibaba.alink.common.utils.OperatorCsvCollector.collectToCsv.
: org.apache.flink.shaded.netty4.io.netty.handler.codec.TooLongFrameException: Response entity too large: DefaultHttpResponse( decodeResult: success, version: HTTP/1.1)
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Access-Control-Allow-Origin: *
The error message "content-length: 118885457 Try to raise [rest.client.max-content-length]" will be displayed.
I followed the message and set "rest.client.max-content-length:600000000" in jobmanager and each taskmanager, but it did not improve the situation.
How can I fix this problem?
[jobmanager_log.txt](https://github.com/alibaba/Alink/files/7494326/jobmanager_log.txt)
[taskmanager_10.0.1.23_52178-5e5e89_log.txt](https://github.com/alibaba/Alink/files/7494329/taskmanager_10.0.1.23_52178-5e5e89_log.txt)
[taskmanager_10.0.1.132_54290-a0709a_log.txt](https://github.com/alibaba/Alink/files/7494331/taskmanager_10.0.1.132_54290-a0709a_log.txt)

**Comment by Fanoid** [comment]
For the second problem, what is the total size of your data? Could you give an estimation?
And which way to use PyAlink?  useLocalEnv or useRemoteEnv or else?

As for the first problem, what do you mean by "cannot connect to jobmanager"? Are there any exceptions?

**Comment by dragonblare** [comment]
Answer from the first question.
The size of the data set is 137MB.
I am trying to use PyAlink's "VectorAssembler" and "SVC" to perform binary classification.
I am using useRemoteEnv to connect to the cluster.

The answer to the following question is that I have downloaded the jar file from PyAlink and put it in the lib folder of Apache Flink. /bin/taskmanager start" from the taskmanager side to connect to the jobmanager.
If I don't put the jar file from PyAlink in the lib folder of the taskmanager side, it works fine.

Sorry for my poor English...

**Comment by dragonblare** [comment]
The cause of this problem was that I didn't put the config in remoteEnv() config. I've solved the problem and will close it.
I'm sorry to have taken up so much of your time.
