### ISSUE TITLE
文件格式有误导致git clone  出错

### ISSUE THREAD

**Issue by weichengzhili** [alibaba/Alink#186]
win10  系统   git clone  之分支代码  报错 
[](
![66YS GC9V}0 C8L9Z6J}QA](https://user-images.githubusercontent.com/36389619/142339708-2ea76da0-6154-4e38-9da2-e9b5dad92325.png)
) 
 出错文件如下：
 docs/cn/批组件/特征工程/特征构造

**Comment by Fanoid** [comment]
Hi, this issue has been fixed.
