### ISSUE TITLE
TableSchema getFieldTypes deprecated

### ISSUE THREAD

**Issue by SteNicholas** [alibaba/Alink#19]
Method `getFieldTypes` of Flink class `TableSchema` is annotated with `Deprecated`, which JIRA is [FLINK-12254 Expose the new type system through the API](https://issues.apache.org/jira/browse/FLINK-12254). It should use method `getFieldDataTypes` instead of `getFieldTypes` to use new type.

**Comment by shaomengwang** [comment]
We'd still be using dataset api until that flink has alternative efficient solution , so the `getFieldTypes` is nessary currently.
