### ISSUE TITLE
Please upload the package to PyPI

### ISSUE THREAD

**Issue by mirekphd** [alibaba/Alink#2]
Most python packages (currently more than 200 thousand) can be easily installed with pip, making it easier to integrate new packages like yours into large existing python development environments. 

This however would require [uploading your package to PyPI](https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56), which I think will be easy with this package, given that it's already bundled into an .egg format.

**Comment by ustcwlin** [comment]
yes, you are right, we are going to upload our package to pypi. we are still working on this pypi package to polish the python code. just wait for a while.
