### ISSUE TITLE
Alink 只支持Python吗？

### ISSUE THREAD

**Issue by xixici** [alibaba/Alink#24]
官方文档里只有pyAlink，请问可以试用其他语言吗？比如Java，Scala

**Comment by qiuxiafei** [comment]
支持java。看这里：https://github.com/alibaba/Alink#%E5%A6%82%E4%BD%95%E5%9C%A8%E9%9B%86%E7%BE%A4%E4%B8%8A%E8%BF%90%E8%A1%8Calink%E7%AE%97%E6%B3%95 。

Java API 与 Python API 基本是一一对应的。
