### ISSUE TITLE
Some wrong

### ISSUE THREAD

**Issue by LeoChep** [alibaba/Alink#25]
试图与flink交互时，表环境不一致错误
Exception in thread "main" org.apache.flink.table.api.ValidationException: Only tables from the same TableEnvironment can be joined.

`
package com.alibaba.alink;

import com.alibaba.alink.operator.batch.BatchOperator;
import com.alibaba.alink.operator.batch.dataproc.SplitBatchOp;
import com.alibaba.alink.operator.batch.recommendation.AlsPredictBatchOp;
import com.alibaba.alink.operator.batch.recommendation.AlsTrainBatchOp;
import com.alibaba.alink.operator.batch.source.CsvSourceBatchOp;
import com.alibaba.alink.operator.batch.source.TableSourceBatchOp;
import org.apache.flink.api.java.DataSet;
import org.apache.flink.api.java.ExecutionEnvironment;
import org.apache.flink.api.java.tuple.Tuple3;
import org.apache.flink.table.api.Table;
import org.apache.flink.table.api.java.BatchTableEnvironment;

public class WrongDemo {
    public static void main(String[] args) throws Exception {
        ExecutionEnvironment env= ExecutionEnvironment.createLocalEnvironment();
        BatchTableEnvironment tEnv= BatchTableEnvironment.create(env);
        String url = "https://alink-release.oss-cn-beijing.aliyuncs.com/data-files/movielens_ratings.csv";
        String schema = "userCol bigint, itemCol bigint,rateCol double, timestamp string";

        Tuple3[] fake= new Tuple3[]{
                new Tuple3<Long,Long,Double>(1L,1L,0.6),
                new Tuple3<Long,Long,Double>(2L,2L,0.8),
                new Tuple3<Long,Long,Double>(2L,3L,0.6),
                new Tuple3<Long,Long,Double>(4L,1L,0.6),
                new Tuple3<Long,Long,Double>(4L,2L,0.3),
        };

        DataSet ds= env.fromElements(fake);
        Table table =tEnv.fromDataSet(ds);

        BatchOperator data=BatchOperator.fromTable(table);
        BatchOperator data3=new TableSourceBatchOp(table);
        SplitBatchOp spliter = new SplitBatchOp().setFraction(0.8);
        BatchOperator data2 = new CsvSourceBatchOp()
                .setFilePath(url).setSchemaStr(schema);

                System.out.println(data.getDataSet().getExecutionEnvironment());
        System.out.println(BatchOperator.getExecutionEnvironmentFromDataSets(ds));
        System.out.println(BatchOperator.getExecutionEnvironmentFromOps(data2));
        System.out.println(BatchOperator.getExecutionEnvironmentFromOps(data3));
        System.out.println(BatchOperator.getExecutionEnvironmentFromOps(spliter.linkFrom(data2)));
        spliter.linkFrom(data);

        BatchOperator trainData = spliter;
        BatchOperator testData = spliter.getSideOutput(0);
        AlsTrainBatchOp als = new AlsTrainBatchOp()
                .setUserCol("userid").setItemCol("movieid").setRateCol("rating")
                .setNumIter(10).setRank(10).setLambda(0.1);
        BatchOperator model = als.linkFrom(trainData);

        AlsPredictBatchOp predictor = new AlsPredictBatchOp()
                .setUserCol("userid").setItemCol("movieid").setPredictionCol("prediction_result");
        BatchOperator preditionResult;

        preditionResult = predictor.linkFrom(model, testData).select("rating, prediction_result");

        preditionResult.print();
    }
}
`

**Comment by Fanoid** [comment]
alink和flink交互的话，可以通过alink里的MLEnvironmentFactory的setDefault来设置flink的env
