### ISSUE TITLE
What's the difference between  Alink and Angel-ML angel

### ISSUE THREAD

**Issue by hermeshephaestus** [alibaba/Alink#3]

**Comment by ustcwlin** [comment]
Alink is using flink engine，but angel-ml is spark based. Two main design points of flink are: one that is well-known is pure streaming, the other is actually iteration operator that does not been mentioned too often. Alink is the effort to leverage this iteration mechanism to improve the algorithm performance and also the machine learning become more and more real-time, so we need a realtime engine to implement those machine learning algorithm
