### ISSUE TITLE
Alink/pyalink/kmeans.ipynb error

### ISSUE THREAD

**Issue by lvchigo** [alibaba/Alink#30]
- use "Alink/pyalink/kmeans.ipynb"
- env:  
![11](https://user-images.githubusercontent.com/8186051/71463632-fe94fd00-27f1-11ea-9add-61ff2afd1ce4.png)  
-  but, step5, error:  
![12](https://user-images.githubusercontent.com/8186051/71463656-14a2bd80-27f2-11ea-8f4b-3ad3389e2fe0.png)

**Comment by Fanoid** [comment]
The error stack is not complete. Please try our latest version to check if the error still exists.
