### ISSUE TITLE
远程执行发生错误

### ISSUE THREAD

**Issue by 0xqq** [alibaba/Alink#34]
val env = ExecutionEnvironment.createLocalEnvironment()
    val tEnv=BatchTableEnvironment.create(env)
    val mle = new MLEnvironment(env, tEnv)
    MLEnvironmentFactory.setDefault(mle) 
加了本地环境 运行提示
 Error:(18, 42) Static methods in interface require -target:jvm-1.8
    val tEnv=BatchTableEnvironment.create(env)

**Comment by Fanoid** [comment]
This error is related to Scala complier options. Please refer to Scala documents to use jvm-1.8.
