### ISSUE TITLE
在线学习FTRL

### ISSUE THREAD

**Issue by krisjin** [alibaba/Alink#5]
在线学习训练支持FTRL ,以后会支持其它的算法吗，问个小白的问题，为什么在线学习只支持线性的，可以解决吗

**Comment by ustcwlin** [comment]
后面会加入更多算法

**Comment by weibozhao** [comment]
线学习不只支持线性，还可以支持一些非线性的算法，比如二阶的在线学习算法

**Comment by krisjin** [comment]
> 在线学习不只支持线性，还可以支持一些非线性的算法，比如二阶的在线学习算法
多谢


> 后面会加入更多算法
多谢

**Comment by krisjin** [comment]
> 在线学习不只支持线性，还可以支持一些非线性的算法，比如二阶的在线学习算法

多谢

**Comment by krisjin** [comment]
> 后面会加入更多算法

期待....
