### ISSUE TITLE
Document lack of the way how to save trained model with Alink trainer

### ISSUE THREAD

**Issue by SteNicholas** [alibaba/Alink#54]
In integration with Alink, I didn't find how to save alink trainer trained model in documents of Alink. In my application, I use `PipelineModel` to save trained model with Alink trainer as follows, but this has no document to describe the way. And I don't know how to save online learning model.
```
Pipeline pipeline = new Pipeline().add(vectorAssembler).add(kMeans);
PipelineModel pipelineModel = pipeline.fit(data);
pipelineModel.save("/tmp/feature_pipe_model.csv");
```

**Comment by weibozhao** [comment]
Online learning models is  a stream models, you need save them to a stream database. If you want to use a saved model, you need to load it from a stream database with special model id. In our pyAlink ftrl demo, we don't save stream models and we use the stream models predicting sample labels directly.

**Comment by SteNicholas** [comment]
@weibozhao In Alink document, there is no anything to mention this point.
