### ISSUE TITLE
Is there a way to save the pipeline model to Mysql?

### ISSUE THREAD

**Issue by xixici** [alibaba/Alink#55]
I try to save the model, use this code:
```
featurePipeline.save(FEATURE_PIPELINE_MODEL_FILE)
```
The pipeline model have been save to a file with csv.
Is there a way to save the model to mysql and load it?

**Comment by SteNicholas** [comment]
@xixici You should refer to the document [写MySQL表](https://github.com/alibaba/Alink/blob/master/docs/cn/mysqlsinkbatchop.md)

**Comment by xixici** [comment]
I mean write  the model to MySql or read the model from Mysql.
The codes like:
```
    // fit and save feature pipeline model
    val FEATURE_PIPELINE_MODEL_FILE: String = "model/feature_pipe_model.csv"
    val featurePipeline: PipelineModel =  feature_pipeline.fit(trainBatchData)
    featurePipeline.save(FEATURE_PIPELINE_MODEL_FILE)

    BatchOperator.execute()

    // load pipeline model
    val featurePipelineModel = PipelineModel.load(FEATURE_PIPELINE_MODEL_FILE)
```
