### ISSUE TITLE
we need the "weight" field result,but alink can't return 

### ISSUE THREAD

**Issue by sparrowzoo** [alibaba/Alink#57]
my schema is 
```
String schema = "f0 bigint, f1 bigint, label double, weight double";
```
input data is 
```
370,2770,1,0.5 1
370,2770,1,0.5 2
83,235,1,0.5 3
273,59315,1,0.5 4
1,31,0,0.6 5
```
follow is my LR output result:

f0|f1|label|weight|pred|pred_detail
--|--|-----|------|----|-----------
1|31|0.0000|0.6000|0.0000|{"0.0":"0.9999988132016909","1.0":"1.1867983090718681E-6"}
370|2770|1.0000|0.5000|1.0000|{"0.0":"0.0","1.0":"1.0"}
273|59315|1.0000|0.5000|1.0000|{"0.0":"0.0","1.0":"1.0"}
83|235|1.0000|0.5000|1.0000|{"0.0":"8.20766454801003E-10","1.0":"0.9999999991792335"}
370|2770|1.0000|0.5000|1.0000|{"0.0":"0.0","1.0":"1.0"}

Alik LR  `pred_detail` only return final result(item's score),we need 'weight' field of LR(not weight of schema).to recompute other score  in our business of recommend system for rank.  so i want alink community can help me to add this function. thanks!!!

**Comment by Pratham31** [comment]
Can you send a source code so that I can help you out?

**Comment by sparrowzoo** [comment]
> Can you send a source code so that I can help you out?

thanks  
my requirement is simple.
 y=wx+b 
we need the "w"
