### ISSUE TITLE
I can't found kafka method in source code, when i use alink_core_flink-1.10_2.1-1.1.0.jar.

### ISSUE THREAD

**Issue by xixici** [alibaba/Alink#58]
I just use pom and import alink_core_flink-1.10_2.1-1.1.0.jar into my project.
Something is wrong like:
```
Error:(89, 17) not found: type Kafka011SourceStreamOp
    val source: Kafka011SourceStreamOp = new Kafka011SourceStreamOp()
```
I also can't found it in the source jar.
Besides, there is no problem when I package the jar myself with alink_1.0.0.
Please check the jar and update it to maven market.

**Comment by chengscu** [comment]
we need this dependency： <dependency>
    <groupId>com.alibaba.alink</groupId>
    <artifactId>alink_connectors_kafka_flink-1.10_2.11</artifactId>
    <version>1.1.0</version>
</dependency>

**Comment by chengscu** [comment]
Try adding this dependency：
`<dependency>
    <groupId>com.alibaba.alink</groupId>
    <artifactId>alink_connectors_kafka_flink-1.10_2.11</artifactId>
    <version>1.1.0</version>
</dependency>`
