### ISSUE TITLE
运行时提示TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by Danielhui** [alibaba/Alink#6]
导入完包后输入useLocalEnv(2, flinkHome=None, config=None)，提示
JVM listening on 127.0.0.1:6327
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
 in 
----> 1 useLocalEnv(2, flinkHome=None, config=None)

D:\python\.venv\lib\site-packages\pyalink-1.0_flink_1.9.0_scala_2.11-py3.7.egg\pyalink\alink\env.pyc in useLocalEnv(parallelism, flinkHome, config)

D:\python\.venv\lib\site-packages\pyalink-1.0_flink_1.9.0_scala_2.11-py3.7.egg\pyalink\alink\env.pyc in make_configuration(config)

D:\python\.venv\lib\site-packages\pyalink-1.0_flink_1.9.0_scala_2.11-py3.7.egg\pyalink\alink\py4j_util.pyc in get_java_gateway()

D:\python\.venv\lib\site-packages\pyalink-1.0_flink_1.9.0_scala_2.11-py3.7.egg\pyalink\alink\py4j_util.pyc in inst(cls)

D:\python\.venv\lib\site-packages\pyalink-1.0_flink_1.9.0_scala_2.11-py3.7.egg\pyalink\alink\py4j_util.pyc in init(self)

TypeError: 'JavaPackage' object is not callable

**Comment by LeoEnze** [comment]
我也遇到了，总感觉是缺包了。炸了

**Comment by Fanoid** [comment]
这个应该是需要Java 8的环境的。

**Comment by cainingnk** [comment]
> 我也遇到了，总感觉是缺包了。炸了

需要是java 8

**Comment by lishuaiiOS** [comment]
我用的是集群安装方式，为何maven打包时候一直报bug，
[ERROR] Failed to execute goal on project alink_core: Could not resolve dependencies for project com.alibaba.alink:alink_core:jar:0.1-SNAPSHOT: Could not transfer artifact net.sf.json-lib:json-lib:jar:2.2.3 from/to alimaven (http://maven.aliyun.com/nexus/content/groups/public): Transfer failed for http://maven.aliyun.com/nexus/content/groups/public/net/sf/json-lib/json-lib/2.2.3/json-lib-2.2.3.jar: Unknown host maven.aliyun.com: Temporary failure in name resolution -> [Help 1]
找不到这个依赖包，我把依赖包导入pom文件还是报这个错

**Comment by xuyang1706** [comment]
> 我用的是集群安装方式，为何maven打包时候一直报bug，
> [ERROR] Failed to execute goal on project alink_core: Could not resolve dependencies for project com.alibaba.alink:alink_core:jar:0.1-SNAPSHOT: Could not transfer artifact net.sf.json-lib:json-lib:jar:2.2.3 from/to alimaven (http://maven.aliyun.com/nexus/content/groups/public): Transfer failed for http://maven.aliyun.com/nexus/content/groups/public/net/sf/json-lib/json-lib/2.2.3/json-lib-2.2.3.jar: Unknown host maven.aliyun.com: Temporary failure in name resolution -> [Help 1]
> 找不到这个依赖包，我把依赖包导入pom文件还是报这个错 。那位大佬知道怎么做，告诉我一下，挺急的

这个问题在另外一个issue里已经解决了。
