### ISSUE TITLE
警告: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS

### ISSUE THREAD

**Issue by geekyouth** [alibaba/Alink#60]
com.alibaba.alink.ALSExample

三月 21, 2020 10:58:26 下午 com.github.fommil.netlib.BLAS <clinit>
警告: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
三月 21, 2020 10:58:26 下午 com.github.fommil.netlib.BLAS <clinit>
警告: Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS
三月 21, 2020 10:58:26 下午 com.github.fommil.netlib.LAPACK <clinit>
警告: Failed to load implementation from: com.github.fommil.netlib.NativeSystemLAPACK
三月 21, 2020 10:58:26 下午 com.github.fommil.netlib.LAPACK <clinit>
警告: Failed to load implementation from: com.github.fommil.netlib.NativeRefLAPACK

![image](https://user-images.githubusercontent.com/12899262/77229289-0a614700-6bc8-11ea-9365-6fc125df5c10.png)

无法加载本地库？？？

**Comment by geekyouth** [comment]
com.alibaba.alink.KMeansExample

三月 21, 2020 11:08:40 下午 com.github.fommil.netlib.BLAS <clinit>
警告: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
三月 21, 2020 11:08:40 下午 com.github.fommil.netlib.BLAS <clinit>
警告: Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS

![image](https://user-images.githubusercontent.com/12899262/77229464-231e2c80-6bc9-11ea-83c6-2b2eab62bd2a.png)

**Comment by chengscu** [comment]
> com.alibaba.alink.ALSExample
> 
> 三月 21, 2020 10:58:26 下午 com.github.fommil.netlib.BLAS
> 警告: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
> 三月 21, 2020 10:58:26 下午 com.github.fommil.netlib.BLAS
> 警告: Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS
> 三月 21, 2020 10:58:26 下午 com.github.fommil.netlib.LAPACK
> 警告: Failed to load implementation from: com.github.fommil.netlib.NativeSystemLAPACK
> 三月 21, 2020 10:58:26 下午 com.github.fommil.netlib.LAPACK
> 警告: Failed to load implementation from: com.github.fommil.netlib.NativeRefLAPACK
> 
> ![image](https://user-images.githubusercontent.com/12899262/77229289-0a614700-6bc8-11ea-9365-6fc125df5c10.png)
> 
> 无法加载本地库？？？

它的意思是无法加载native的blas库，此时会转而加载用java实现的blas库，性能会有一些损失，但不影响正确性。
