### ISSUE TITLE
为何maven打包说缺依赖

### ISSUE THREAD

**Issue by lishuaiiOS** [alibaba/Alink#7]
我用的是集群安装方式，为何maven打包时候一直报bug，
[ERROR] Failed to execute goal on project alink_core: Could not resolve dependencies for project com.alibaba.alink:alink_core:jar:0.1-SNAPSHOT: Could not transfer artifact net.sf.json-lib:json-lib:jar:2.2.3 from/to alimaven (http://maven.aliyun.com/nexus/content/groups/public): Transfer failed for http://maven.aliyun.com/nexus/content/groups/public/net/sf/json-lib/json-lib/2.2.3/json-lib-2.2.3.jar: Unknown host maven.aliyun.com: Temporary failure in name resolution -> [Help 1]
找不到这个依赖包，我把依赖包导入pom文件还是报这个错 。那位大佬知道怎么做，告诉我一下，挺急的

**Comment by lishuaiiOS** [comment]
[ERROR] Failed to execute goal on project alink_core: Could not resolve dependencies for project com.alibaba.alink:alink_core:jar:0.1-SNAPSHOT: The following artifacts could not be resolved: org.apache.flink:flink-runtime_2.11:jar:1.9.0, org.apache.flink:flink-table-planner_2.11:jar:1.9.0, net.sf.json-lib:json-lib:jar:2.2.3, org.scala-lang:scala-compiler:jar:2.11.11, org.scalanlp:breeze_2.11:jar:0.11.2: Could not transfer artifact org.apache.flink:flink-runtime_2.11:jar:1.9.0 from/to central (https://repo.maven.apache.org/maven2): GET request of: org/apache/flink/flink-runtime_2.11/1.9.0/flink-runtime_2.11-1.9.0.jar from central failed: Read timed out -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :alink_core

**Comment by qiuxiafei** [comment]
检查一下是不是网络环境的问题，mvn.aliyun.com和mvn central 都是可以公开访问的。
