### ISSUE TITLE
[Ver 1.1.1] Issue when running useLocalEnv()

### ISSUE THREAD

**Issue by lcr95** [alibaba/Alink#76]
Getting error when running `useLocalEnv(2) `

>~\Anaconda3\lib\site-packages\pyalink\alink\config.py in _get_default_local_ip()
      5 def _get_default_local_ip():
      6     cmd = '''ifconfig eth0|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "addr:"'''
----> 7     local_ip = subprocess.check_output(cmd, shell=True, stderr=subprocess.DEVNULL).decode("utf-8").strip()
      8     if local_ip is None or local_ip == '':
      9         local_ip = "localhost"

>CalledProcessError: Command 'ifconfig eth0|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "addr:"' returned non-zero exit status 255.

**Comment by Fanoid** [comment]
Sorry for inconvenience. Please use version 1.1.0 for now.
