### ISSUE TITLE
希望Alink支持keyby("metricId")加载不同模型，然后对不同流进行预测

### ISSUE THREAD

**Issue by tammyzhang123** [alibaba/Alink#79]
场景：flink对不同指标通过keyby("metricId")的方式加载不同模型，然后对不同流进行数据预测
现有问题点：在flink窗口函数中加载训练好的模型进行预测的话，会出现job失败的问题，见#78
目前支持场景为单一指标模型的实时预测，但是还不能支持多指标（比如指标量达到1w+）的并行预测，希望后续能够支持

**Comment by shaomengwang** [comment]
参考 #78 解决
