### ISSUE TITLE
为何easy_install安装失败

### ISSUE THREAD

**Issue by lishuaiiOS** [alibaba/Alink#8]
我没学过python，在python这方面小白，我安装python3.5的环境，也下载包了，但是按照提示easy_install时候报错，官方提供的是easy_install [存放的路径]/pyalink-0.0.1-py3.*.egg。我的是easy_install   /usr/apps/pyalink-1.0_flink_1.9.0_scala_2.11-py3.5.egg  为何跑了很久一直卡在Couldn't find index page for 'pyalink' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
卡的有半小时多，最后报错说找不到pyalink-1.0_flink_1.9.0_scala_2.11-py3.5，有安装成功的么？试了好多次都不行，有人懂么？在线等，挺急的

**Comment by Fanoid** [comment]
这种情况一般是有Python2和3共存导致的，可以用python --version看到默认使用的版本。
安装的话，你这种情况应该需要用easy_install-3.5来进行安装。（文档里其实有说明）

**Comment by Fanoid** [comment]
> 我没学过python，在python这方面小白，我安装python3.5的环境，也下载包了，但是按照提示easy_install时候报错，官方提供的是easy_install [存放的路径]/pyalink-0.0.1-py3.*.egg。我的是easy_install /usr/apps/pyalink-1.0_flink_1.9.0_scala_2.11-py3.5.egg 为何跑了很久一直卡在Couldn't find index page for 'pyalink' (maybe misspelled?)
> Scanning index of all packages (this may take a while)
> Reading https://pypi.org/simple/
> 卡的有半小时多，最后报错说找不到pyalink-1.0_flink_1.9.0_scala_2.11-py3.5，有安装成功的么？试了好多次都不行，有人懂么？在线等，挺急的

这种情况一般是有Python2和3共存导致的，可以用python --version看到默认使用的版本。
安装的话，你这种情况应该需要用easy_install-3.5来进行安装。（文档里其实有说明）

**Comment by lishuaiiOS** [comment]
> > 我没学过python，在python这方面小白，我安装python3.5的环境，也下载包了，但是按照提示easy_install时候报错，官方提供的是easy_install [存放的路径]/pyalink-0.0.1-py3.*.egg。我的是easy_install /usr/apps/pyalink-1.0_flink_1.9.0_scala_2.11-py3.5.egg 为何跑了很久一直卡在Couldn't find index page for 'pyalink' (maybe misspelled?)
> > Scanning index of all packages (this may take a while)
> > Reading https://pypi.org/simple/
> > 卡的有半小时多，最后报错说找不到pyalink-1.0_flink_1.9.0_scala_2.11-py3.5，有安装成功的么？试了好多次都不行，有人懂么？在线等，挺急的
> 
> 这种情况一般是有Python2和3共存导致的，可以用python --version看到默认使用的版本。
> 安装的话，你这种情况应该需要用easy_install-3.5来进行安装。（文档里其实有说明）

我们确实有2个python版本 python -V是2.7.5 ，python3 -V是3.7，不小心昨天把python3.5升级到了3.7。我下个pyalink3.7的包用easy_install3.7试试安装一下

**Comment by lishuaiiOS** [comment]
> > 我没学过python，在python这方面小白，我安装python3.5的环境，也下载包了，但是按照提示easy_install时候报错，官方提供的是easy_install [存放的路径]/pyalink-0.0.1-py3.*.egg。我的是easy_install /usr/apps/pyalink-1.0_flink_1.9.0_scala_2.11-py3.5.egg 为何跑了很久一直卡在Couldn't find index page for 'pyalink' (maybe misspelled?)
> > Scanning index of all packages (this may take a while)
> > Reading https://pypi.org/simple/
> > 卡的有半小时多，最后报错说找不到pyalink-1.0_flink_1.9.0_scala_2.11-py3.5，有安装成功的么？试了好多次都不行，有人懂么？在线等，挺急的
> 
> 这种情况一般是有Python2和3共存导致的，可以用python --version看到默认使用的版本。
> 安装的话，你这种情况应该需要用easy_install-3.5来进行安装。（文档里其实有说明）

怎么安装easy_install-3.7  我们系统有个easy_install 和easy_install-2.7 。不知道怎么升级，或者安装easy_install-3.7，网上也没找到答案

**Comment by Fanoid** [comment]
> 怎么安装easy_install-3.7 我们系统有个easy_install 和easy_install-2.7 。不知道怎么升级，或者安装easy_install-3.7，网上也没找到答案

你这个实际上是系统和Python的问题了。一般通过系统的包管理或者`pip install setuptools`就好了，用pip的话也要注意版本。

**Comment by lishuaiiOS** [comment]
> > 怎么安装easy_install-3.7 我们系统有个easy_install 和easy_install-2.7 。不知道怎么升级，或者安装easy_install-3.7，网上也没找到答案
> 
> 你这个实际上是系统和Python的问题了。一般通过系统的包管理或者`pip install setuptools`就好了，用pip的话也要注意版本。

多谢大佬  网上一直没找到答案
