### ISSUE TITLE
Research and development of FFM algorithm based on alink platform

### ISSUE THREAD

**Issue by cainingnk** [alibaba/Alink#82]
基于Alink平台的FFM算法探索及研发

* 描述
自2010年FM被提出后，该算法被广泛应用到各个业务领域，并且取得了很好的业务效果。2016年提出的FFM算法是FM的升级版，引入了field的概念，它把相同性质的特征归于同一个field。近几年，学术界的很多科研工作者在FFM算法研究方面也做出了很多创新性工作，类似OCFFM、Bilinear-FFM、 DeepFFM、FAT-DeepFFM、DeepFaFM等。希望参与该项目的同学能调研前沿的FFM算法（不限于上面的算法），并筛选出若干优秀的算法进行开发。
目标：在Alink 平台基础上，设计并开发若干前沿FFM算法，复现文章中的试验结果，并开发算法对应的单元测试及功能测试。Alink平台提供了高效的共性函数库以及丰富的数据源组件，参与项目的同学在算法开发中可以合理使用Alink平台的这些共性函数库及数据源组件，最终开发出若干高效的前沿FFM算法。

* 需要技能
  1.良好的Java开发能力；
  2. 熟悉机器学习算法；
  3. 熟悉分布式算法开发；
  4. 具有较好的数学基础；
  5. 熟悉Alink算法开发。

Research and development of FFM algorithm based on alink platform

* Description
since FM was proposed in 2010, the algorithm has been widely used in various application areas, and achieved good results. The FFM algorithm proposed in 2016 is an upgraded version of FM, which introduces the concept of field, and attributes the same characteristics to the same field. In recent years, many researchers in the academic circle have also made a lot of innovative work in FFM algorithm research, such as OCFFM, bilinear FFM, deepFFM, FAT- deepFFM, etc. It is hoped that the students involved in the project can investigate the FFM algorithm (not limited to the above algorithm), and select several excellent algorithms for development.
Goal: on the basis of alink platform, design and develop a number of cutting-edge FFM algorithms, reproduce the test results in the articles, and develop the unit test and function test corresponding to the algorithm. Alink platform provides efficient common function library and rich data source components. Students participating in the project can reasonably use these common function library and data source components of alink platform in algorithm development, and finally develop several efficient cutting-edge FFM algorithms.

* Skills required
  1. Good java development ability; 
  2. Familiar with machine learning algorithm; 
  3. Familiar with distributed algorithm development; 
  4. Good mathematical foundation; 
  5. Familiar with alink algorithm development.

reference：
[1] Alink: https://github.com/alibaba/Alink
[2] Zhang J, Huang T, Zhang Z. FAT-DeepFFM: Field Attentive Deep Field-aware Factorization Machine[J]. arXiv preprint arXiv:1905.06336, 2019.
[3] Huang T, Zhang Z, Zhang J. FiBiNET: combining feature importance and bilinear feature interaction for click-through rate prediction[C]//Proceedings of the 13th ACM Conference on Recommender Systems. 2019: 169-177.
[4] Yuan B, Yang M Y, Hsia J Y, et al. One-class Field-aware Factorization Machines for Recommender Systems with Implicit Feedbacks[R]. Technical Report. National Taiwan University, 2019.

**Comment by NitishGadangi** [comment]
Hey @cainingnk 
I really like this idea and would like to work on this summer. I will do required research and get back.

**Comment by cainingnk** [comment]
@NitishGadangi Thank you for your attention. please refer to https://developer.aliyun.com/topic/summerofcode2020 and #85.
