### ISSUE TITLE
Research and development of linear programming algorithm based on alink platform

### ISSUE THREAD

**Issue by cainingnk** [alibaba/Alink#83]
基于Alink平台的线性规划系列算法研发
* 描述
线性规划（Linear programming,简称LP），是运筹学中研究较早、发展较快、应用广泛、方法较成熟的一个重要分支，它是辅助人们进行科学管理的一种数学方法。研究线性约束条件下线性目标函数的极值问题的数学理论和方法。线性规划是运筹学的一个重要分支，广泛应用于军事作战、经济分析、经营管理和工程技术等方面。为合理地利用有限的人力、物力、财力等资源作出的最优决策，提供科学的依据。
* 目标
1. 线性规划求解算法开发。要求分别实现单纯形法和内点法。
2. 0-1整数规划算法开发。求解算法不限，要求算法适合于并行，可扩展性好，计算规模大。
* 要求
1. 基于Alink平台实现。
2. 设计合理易用的接口，接口形式和规范与其它Alink组件保持一致。
3. 算法要求支持分布式，可扩展性好，计算规模和计算性能达到前沿水平。
需要技能：1. 良好的Java开发能力；2. 熟悉运筹优化算法；3. 熟悉分布式算法开发；4. 具有较好的数学基础。

* Description
Linear programming (LP for short) is an important branch of operational research, which has been studied earlier, developed faster, applied widely and has mature methods. It is a mathematical method to assist people in scientific management. This paper studies the mathematical theory and method of the extremum problem of linear objective function under linear constraints. Linear programming is an important branch of operational research, which is widely used in military operations, economic analysis, business management and engineering technology. It can provide scientific basis for the optimal decision making of rational use of limited human, material and financial resources.

* Goal
1. Development of linear programming algorithm. Simplex method and interior point method are required.
2. 0-1 integer programming algorithm development. There is no limit to the algorithm, which requires the algorithm to be suitable for parallel, good scalability and large computing scale.

* requirement
1. Implementation based on alink platform.
2. Design a reasonable and easy-to-use interface. The interface form and specification shall be consistent with other alink components.
3. The algorithm needs to support distributed, good scalability, and the computing scale and performance reach the forefront level.
Skills required: 1. Good java development ability; 2. Familiar with operation research optimization algorithm; 3. Familiar with distributed algorithm development; 4. Good mathematical foundation

**Comment by hastagAB** [comment]
Hi @cainingnk ,
I'm very glad to see a research-oriented project for ASoC. I would like to work on implementing the LP algorithm on Alink this summer.
Do we have a getting started guide for the Alink project to get to know the codebase a little bit?

**Comment by cainingnk** [comment]
@hastagAB Thank you for your attention. please refer to  https://developer.aliyun.com/topic/summerofcode2020 and  https://github.com/alibaba/Alink/issues/85.

**Comment by Pratham31** [comment]
Hi @cainingnk ,
I found it very interesting for a research-oriented project for ASoC.But is it mandatory to implement an algorithm with the help of java?

**Comment by Pratham31** [comment]
HI @cainingnk ,
Do we have to implement both simplex and interior-point methods?
