### ISSUE TITLE
Research and development of time series anomaly detection algorithm based on alink platform

### ISSUE THREAD

**Issue by cainingnk** [alibaba/Alink#84]
基于Alink平台的时间序列异常检测探索和研发
* 描述
在时间序列分析领域，时序分解是一种常见的方法，它将时间序列分成几个部分：周期性(季节项)、趋势性、节假日效应，以及部分异常值(剩余项)。对时间序列进行异常检测也是常见的方式。
 
* 要求
1. 周期性，使用傅里叶级数建立周期模型
2. 趋势性，饱和增长模型和分段线性模型，支持加入变化点(变化点服从laplace分布) 
3. 节假日与突发事件模型：可以指定节假日，以及前后相关的天数
4. 能够处理缺失值和数据时间非等距情况
 
* 开发要求
1. 基于Alink平台实现
2. 使用java语言
3. 设计合理的接口，接口形式和规范与其它Alink组件保持一致
4. 有完备的UT，FT和文档
 
* 预期成果
1.实现一种或多种时间序列异常检测方法
2.效果和同类的算法或者软件持平

* 需要的技能
1. 良好的Java开发能力
2. 熟悉时间序列算法
3. 熟悉异常检测方法
4. 具有较好的数学基础

* Description
In the field of time series analysis, time series decomposition is a common
method, which divides time series into several parts: periodicity (seasonal),
trend, holiday effect, and some outliers (residual). Anomaly detection of time
series is also a common way.
 
* Timeseries method requirements:
1.Periodicity, use Fourier series to establish periodic model
2.Trend, saturated growth model and piecewise linear model, support to add change
points (change points obey Laplace distribution)
3.Holidays and emergencies model: you can specify holidays and related days
4.Be able to handle the situation of missing value and unequal data time Development

* requirements
1. Based on Alink platform and use java language
2. Reasonably designed interface, the interface form and specifications are consistent with other Alink components
3. complete UT, FT and documents
 
* Goal
1. Implement one or more time series anomaly detection methods
2. The effect is equal to similar algorithms or software
 
* Skills required
1. Good Java development ability
2. Familiar with time series algorithm
3. Familiar with anomaly detection methods
4. Have a good mathematical foundation

**Comment by Kaushl2208** [comment]
Hey @cainingnk, This idea seems pretty interesting to me and I would love to work on it this summer. Are there any discussions platform where we can discuss the project further?

**Comment by cainingnk** [comment]
@Kaushl2208 Thank you for your attention. please refer to  https://developer.aliyun.com/topic/summerofcode2020 and  https://github.com/alibaba/Alink/issues/85.
