### ISSUE TITLE
📢Alibaba Summer of Code 2020

### ISSUE THREAD

**Issue by cainingnk** [alibaba/Alink#85]
Welcome to the open source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and coding with us! 💻

Alibaba Summer of Code is a global program focused on engaging students directly into open source software development. Under the guidance of the mentor in the Alibaba open source project, students experience the software development in the real world.Alibaba Summer of code will begin between May 25th and September 5th. Students can use the summer time to participate in the open source project and work with the core members of the project.

## What you can get
On this exclusive developer journey, you will have the opportunity to:

Participate in the top projects of the International Open Source Foundation;
Get a scholarship from Alibaba;
Obtain an open source contributor certificate;
Get a fast pass of Alibaba Internship/recruitment;
Get your code adopted and used by the open source project！

## Our Mentor
Ning Cai(@cainingnk )
Weibo Zhao(@weibozhao)

## Apply Now!
Idea list (feel free to submit new ideas):
* https://github.com/alibaba/Alink/labels/ASoC2020

You can click on this link to apply directly:

* Chinese: https://developer.aliyun.com/topic/summerofcode2020
* English: https://www.alibabacloud.com/campaign/summerofcode2020

## Timeline⏳

![image](https://user-images.githubusercontent.com/35248320/82629037-1fd30b80-9c21-11ea-82e1-120496f11ce1.png)

## Contact us!
Email Address:

**Comment by yangzm11** [comment]
@cainingnk  @weibozhao  

Hello, I have just noticed ASOC 2020 and I am really interested in Alink. May I submit submit a new idea?

I expect to implement Mixed Integer Linear Programming (MILP). MILP is for Combinatorial Problem solving, while linear programming is for continuous problems. 

I can develop Cutting Plane Method and Branch & Bound Method to solve MILP. Besides, I can also develop intelligent algorithms such as Genetic Algorithm (GA) and Particle Swarm Optimization (PSO).
