### ISSUE TITLE
这个项目烂尾了吗

### ISSUE THREAD

**Issue by cfgxy** [alibaba/Alink#89]
生产级有人用吗？
刚开始用就遇到MySQLSourceBatch 的坑，多个DB下有同名table就不支持了。
想用一下Word2Vec，根据Python版Demo转写成Java根本跑不起来，各种NullPointerException; 想改源码吧，Java文档少的可怜，无从下手

**Comment by shaomengwang** [comment]
这些问题的现场可以提供一下吗

**Comment by shaomengwang** [comment]
Alink我们一直在持续的更新迭代，欢迎多多的提建议，也可以加入首页的钉钉群，保持沟通，有时间也可以贡献代码到Alink，大家一起共建
