### ISSUE TITLE
关于Build Project的一些问题

### ISSUE THREAD

**Issue by k765498** [alibaba/Alink#91]
在build project时，只能使用java8，更高的例如java14是不是无法完成build？以及对于使用的scala的版本时必须在2.11吗？

**Comment by k765498** [comment]
在build project时，只能使用java8，更高的例如java14是不是无法完成build？以及对于使用的scala的版本时必须在2.11吗？

**Comment by ZhangYuef** [comment]
> 在build project时，只能使用java8，更高的例如java14是不是无法完成build？以及对于使用的scala的版本时必须在2.11吗？

Java版本根据README应该是官方推荐Java 8，
